### ISSUE TITLE
support for python3

### ISSUE THREAD

**Issue by GliderGeek** [vallettea/koala#115]
would be great if this package would support python3
it seems that the dependencies are all python3 ready

**Comment by vallettea** [comment]
Feel free to PR

Envoyé de mon iPhone

**Comment by GliderGeek** [comment]
great, thanks btw for the quick action on the requirements merge 👍

**Comment by chinobing** [comment]
Thanks for the great work. waiting for the python 3 support

**Comment by Brad-eki** [comment]
I have run the tests for commit c8316fa from jricardo27 in Python 2.7, 3.4, 3.5 and 3.6 (https://github.com/anthill/koala/tree/c8316fa87b9c21b6c0e956438c18894d08fdf792).

There are a couple of changes required, however I was running a later version of networkx. 

In netwokrx, signatures and return datatypes have changed on DiGraph add_node, successors and successors_iter.  This mainly affects ast/* and Spreadsheet.py. 

Also, /koala-c8316fa87b9c21b6c0e956438c18894d08fdf792/koala/openpyxl/xml does not contain namespace.py. I'm still figuring if this is intentional (my guess is this is an omission)

Notes on DiGraph successors:

- https://networkx.github.io/documentation/networkx-1.9/_modules/networkx/classes/digraph.html#DiGraph.successors
- https://networkx.github.io/documentation/networkx-1.9/_modules/networkx/classes/digraph.html#DiGraph.successors_iter
- https://networkx.github.io/documentation/networkx-2.1/_modules/networkx/classes/digraph.html#DiGraph.successors
        
DiGraph add_node:
- https://networkx.github.io/documentation/networkx-1.9/_modules/networkx/classes/digraph.html#DiGraph.add_node
- https://networkx.github.io/documentation/networkx-2.1/_modules/networkx/classes/digraph.html#DiGraph.add_node

I will commit the code I have which requires the following:
networkx==2.1
openpyxl==2.5.3
numpy==1.14.2
Cython==0.28.2
lxml==4.1.1
six==1.11.0

If someone tests verifies c8316fa before me, awesome but, besides namespace.py, I expect that it works with the original dependancy requirements.

**Comment by vallettea** [comment]
it is an omission.
Waiting for you commit, thanks for the work.

**Comment by Brad-eki** [comment]
how do we get pypi.org to take on 0.0.18?

**Comment by vallettea** [comment]
Sorry i forgot to push. I’ll do it wednesday

Envoyé de mon iPhone

**Comment by vallettea** [comment]
Had some time, just did it.

**Comment by Brad-eki** [comment]
Fantastic. Thanks vallettea. Much appreciated.

**Comment by Brad-eki** [comment]
@vallettea I'm sure we can close this one :D
