### ISSUE TITLE
Running the package on python 3

### ISSUE THREAD

**Issue by Alerq** [vallettea/koala#127]
Please, write some understandable instruction on how to run the package for those who use python 3. 
Sadly, as a beginner, I don't understand hints like "just use futurize".

Thank you a lot for your kindness and time!

**Comment by ulternate** [comment]
The master branch looks to be Python 3 compatible, as the code was updated using `futurize` already and that was merged in PR #125. The issue is that the package on PyPI hasn't been updated yet.

I'm doing the following to grab the latest code from the master branch (in my `requirements.txt` file for `pip install -r requirements.txt`):
```
-e git+https://github.com/anthill/koala@master#egg=koala2
```

**Comment by Brad-eki** [comment]
ulternate, the latest version (0.0.18) is now Python 3 ready and tests are successful in Python 2.7, 3.4, 3.5 and 3.6. It includes support for networkx 2.1.

The latest version was pushed to PyPI was updated a few hours ago by vallettea. I was able to pip install koala2 and get 0.0.18.

**Comment by ulternate** [comment]
Cool, must have been recently updated. I looked this morning and saw PyPI still showing 0.0.17 as the latest. Cheers.
