### ISSUE TITLE
Excel functions: mid

### ISSUE THREAD

**Issue by Korella** [vallettea/koala#162]
It's [changed](https://github.com/dgorissen/pycel/blob/master/src/pycel/excellib.py). 
And tests also doestn't cover some new conditions.
Probably there is more than one outdated realisation.

**Comment by Brad-eki** [comment]
How has it changed?

**Comment by Korella** [comment]
@Brad-eki 
`return str(text)[start_num:start_num + int(num_chars)]`
**start_num + int(num_chars)** is kinda significant

**Comment by Brad-eki** [comment]
Would you be able to explain to me how it might be fixed? (please assume I know nothing about it)

**Comment by Brad-eki** [comment]
@Korella, after some investigation I can agree the mid function does not behave the same as Excel. In terms of Koala, it appears as though this has been the case since the beginning. The PyCel code looks to have been updated with something similar to the solution you've put forward here.

I can't find a pull request which offers the code you have suggested:
```python
return str(text)[start_num:start_num + int(num_chars)]
```
Would you like to have a go at making the change and updating the tests for mid so it doesn't revert?

**Comment by Brad-eki** [comment]
The behavior of MID has been changed to (start, offset) instead of (start_index, end_index)
